### ISSUE TITLE
Plugin timings do not get grouped up under the plugin

### ISSUE THREAD

**Issue by bergerkiller** [aikar/minecraft-timings#2]
When you add a new timings using the library in the standard way, such as:
```
MCTimings timings = TimingManager.of(plugin).of(name); // init code

timings.startTiming();
// <execute code you wish to time>
timings.stopTiming();
```

Where plugin is your plugin instance, and name is, say, "MinecartGroup::doPhysics()", the results get written to the timings file like so:
`    MinecartGroup::doPhysics() Time: 1195531598 Count: 1606 Avg: 744415 Violations: 7`

The plugin information is dropped from the saved file. As a result, when you view the paste using the spigot API, it shows up under the other Minecraft timings: https://timings.spigotmc.org/?url=visinidipo

A workaround I'm using right now is to explicitly write the plugin information myself, by prepending it to the name of the timings entry.
```
    private static String getTimingName(Plugin plugin, String name) {
        return String.format("Task: %s v%s Runnable: %s",
                plugin.getName(),
                plugin.getDescription().getVersion(),
                name);
    }
```

See also: https://www.spigotmc.org/threads/spigot-timings-making-your-own.285009/#post-2761342

Is this desired behavior or a bug?

**Comment by aikar** [comment]
Sorry I missed this report, which relates to our discussion on timings repo itself.

This is a limitation of the V1 API, which I corrected in V2.

I sadly did not enforce plugin binding in the V1 API, which means those objects are completely arbitrary.

So your workaround will be the only way to do it for v1, unless md5 adds special format rules to his fork of my web parser that I could ensure consistency of in this project, but i dont see that happening.
